# Generated by Django 5.1 on 2024-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_name',
            field=models.CharField(max_length=20),
        ),
    ]
