# Generated by Django 5.1 on 2024-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_alter_jobapplication_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='company_images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
    ]
