# Generated by Django 5.1 on 2024-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
    ]
