# Generated by Django 5.1 on 2024-08-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=50)),
                ('phno', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
