# Generated by Django 5.1 on 2024-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_loginrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter_text', models.TextField(blank=True, null=True)),
                ('cover_letter_file', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
            ],
        ),
    ]
