# Generated by Django 5.1 on 2024-10-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
